export enum ActionCarType {
  RETRIEVE = "RETRIEVE",
  RETRIEVE_SINGLE_CAR = "RETRIEVE_SINGLE_CAR",
  ADD = "ADD",
  EDIT = "EDIT",
  DELETE = "DELETE",
  ADD_ERROR = "ADD_ERROR",
  EDIT_ERROR = "EDIT_ERROR",
  DELETE_ERROR = "DELETE_ERROR",
  RETRIEVE_ERROR = "RETRIEVE_ERROR",
  RETRIEVE_SINGLE_CAR_ERROR = "RETRIEVE_SINGLE_CAR",
  CLEAR_CARS = "CLEAR_CARS",
}