export enum ActionType {
  RETRIEVE = 'RETRIEVE',
  RETRIEVE_ERROR = 'RETRIEVE_ERROR',
  RETRIEVE_SINGLE_CUSTOMER = 'RETRIEVE_SINGLE_CUSTOMER',
  RETRIEVE_SINGLE_CUSTOMER_ERROR = 'RETRIEVE_SINGLE_CUSTOMER_ERROR',
  ADD = 'ADD',
  ADD_ERROR = 'ADD_ERROR',
  EDIT = 'EDIT',
  EDIT_ERROR = 'EDIT_ERROR',
  DELETE = 'DELETE',
  DELETE_ERROR = 'DELETE_ERROR',
  CLEAR_CUSTOMERS = 'CLEAR_CUSTOMERS',
}