export enum ActionType {
  RETRIEVE = 'RETRIEVE',
  ADD = 'ADD',
  ADD_ERROR = 'ADD_ERROR',
  EDIT = 'EDIT',
  EDIT_ERROR = 'EDIT_ERROR',
  DELETE = 'DELETE',
  DELETE_ERROR = 'DELETE_ERROR',
  CLEAR_CUSTOMERS = 'CLEAR_CUSTOMERS',
}